language: c

matrix:
  include:
    - os: osx
      osx_image: xcode9
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode8.2
    - os: osx
      osx_image: xcode8.1
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode6.4
    - os: linux
      env:
        - secure: "BW2vIKQQihbW5Mt9zZwvA+E8t+c/LluCZsKTqbMvl92HwIUEWad05FqP1lT5tzhKE5rBYykgpL3Z7LQKwCxeZzQb+6dVm9YOCGf1T/uKoIig0vrifKmqgOezHV69VxYP3Jez/QvEJMHFgm9HtIkvKUL5sXX7cfL/KjfXctimcvR71oG1WnzUZLMDYRpoFrd/JFX9O1EXUvOJNYN5zwwOLV4AANw0s/7WBHqqkBcO/zcJn/zsYAy5tjoR4TnPdlyvgfLMVY2CA5ja4OfCKr6TYICVyueKSavgQPaFSh+jN8DIpSKm3k1Gzg9Qkb5Riz1rVdSnnfbhE5ysac/6tF/WZCN457S+lvpMO6H5l+7/Wj3C95WtJ6SHum1mjgDDgD+jhxal0t9sKPXwg3mhlGRmYfH4LVjzSFIjzPHXAN5rNJ3o8AedIKVqIAJ0fod3AA6s/wx6pPS2YeRi57gZPSAGFQRAnsrOHiRAv2bfb9q6meAFJeLCglqgjEsCeRZ3J5oOXdBYIQ8S++fc3ULTzv4ovpSAkSUTLetuYmGqstL81sePZ+K5HsS7B/0PtwjEaXTj0ZTPSv1RY2Kms5hwAPLEQLcG2ZfbarDYNN0iefFrFNqUWMsghoEuG2XEG/dAkjQOn34CSTxrJZRYlW+bIpZ7UldPGeuIFpr/pujZu1cdlok="
      addons:
        coverity_scan:
          project:
            name: "mennis/plan9port"
            description: "Build submitted via Travis CI"
          notification_email: mennis@corvus.net
          build_command: "./INSTALL"
          branch_pattern: master
          
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install Caskroom/cask/osxfuse; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-; fi

script:
  - ./INSTALL
